name: Deploy to Amazon Lambda and AWS API Gateway

on:
  push:
    branches:
      - main
      - stage
      - develop

env:
  AWS_REGION: ap-southeast-1               
  ECR_REPOSITORY: awslambda-fastapi 
  FUNCTION_PREFIX: awslambda-fastapi

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/stage'

    steps:
      - name: Set Lambda Functions to Update
        id: setlambda
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "::set-output name=apilambda::$FUNCTION_PREFIX-api-prod"
            echo "::set-output name=workerlambda::$FUNCTION_PREFIX-worker-prod"
          fi

          if [[ "${{github.base_ref}}" == "stage" || "${{github.ref}}" == "refs/heads/stage" ]]; then
            echo "::set-output name=api_lambda::$FUNCTION_PREFIX-api-stage"
            echo "::set-output name=workerlambda::$FUNCTION_PREFIX-worker-stage"
          fi

          if [[ "${{github.base_ref}}" == "develop" || "${{github.ref}}" == "refs/heads/develop" ]]; then
            echo "::set-output name=apilambda::$FUNCTION_PREFIX-api-dev"
            echo "::set-output name=workerlambda::$FUNCTION_PREFIX-worker-dev"
          fi    
          
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to AWS Lambda.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: AWS API Lambda Deploy
        env:
          LAMBDA_FUNCTION_NAME: ${{ steps.setlambda.outputs.apilambda }} 
          IMAGE_URI: ${{ steps.build-image.outputs.image }}
        run: aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --image-uri $IMAGE_URI

      # - name: AWS Worker Lambda Deploy
      #   run: |
      #     aws lambda update-function-code \
      #      --function-name ${{ steps.setlambda.outputs.workerlambda }}
      #      --image-uri ${{ steps.build-image.outputs.image }}

      # - name: AWS API Lambda Deploy
      #   uses: appleboy/lambda-action@master
      #   with:
      #     function_name: awslambda-fastapi-dev-api
      #     image_uri: ${{ steps.build-image.outputs.image }}